version: '3'
services:
  namesrv:
    image: apache/rocketmq:4.6.0
    command: sh mqnamesrv
    ports:
      - "9876:9876"
  broker:
    image: apache/rocketmq:4.6.0
    command: sh mqbroker -n namesrv:9876 -c /broker.conf
    ports:
      - "10909:10909"
      - "10911:10911"
    volumes:
      - ./broker.conf:/broker.conf
  dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=namesrv:9876"
